services:
  - type: web
    name: Tell-A-Doc Backend API
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mysite.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: Tell-A-Doc_django_db
          property: connectionString

databases:
  - name: Tell-A-Doc_django_db
    databaseName: Tell-A-Doc_django_db
    user: Bernard_django_user